Repository Kernel-GL-HRK/gl-kernel-training-2021, pull requests merged in 2021-03, with the labels that each got.

#46 Task4: Basic data structures (linked list)
  04_basic_struct/BBB_log_task4.txt
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/checkpatch.log
  04_basic_struct/task4_module.c
Labels: Ready for review

#54 04_basic_structe implementation
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/khmod.c
  04_basic_struct/logs/sysfs.log
  04_basic_struct/tests.sh
Labels: Ready for review

#55 Debug procfs solution
  05_debug/README.md
  05_debug/procfs/Makefile
  05_debug/procfs/debug_procfs.c
  05_debug/procfs/log.txt
Labels: Ready for review

#57 04_basic_struct: Basic structure homework
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/hello_list.c
  04_basic_struct/setup.sh
Labels: Change requested

#56 03 module homework
  03_module/Makefile
  03_module/README.md
  03_module/simple_module.c
  03_module/test_simple_module.log
  03_module/test_simple_module.sh
Labels: Ready for review

#48 04_basic_struct: module implementation
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/checkpatch.log
  04_basic_struct/lds_module.c
  04_basic_struct/lds_module.log
Labels: Ready for review

#26 Bash homework
  hwdetect/README.md
  hwdetect/bbb_log.txt
  hwdetect/hwdetect.sh
Labels: Ready for review

#63 Time userspace solution
  06_timers/README.md
  06_timers/userspace/Makefile
  06_timers/userspace/log.txt
  06_timers/userspace/time.c
Labels: Ready for review

#60 Task 5: sysfs and procfs
  05_debug/README.md
  05_debug/procfs_uppercase/Makefile
  05_debug/procfs_uppercase/checkpatch.log
  05_debug/procfs_uppercase/procfs_uppercase_module.c
  05_debug/sysfs_lowercase/BBB_log_procfs_uc_converter.txt
  05_debug/sysfs_lowercase/BBB_log_sysfs_lc_converter.txt
  05_debug/sysfs_lowercase/Makefile
  05_debug/sysfs_lowercase/checkpatch.log
  05_debug/sysfs_lowercase/sysfs_lowercase_module.c
Labels: Ready for review

#59 05 debug homework, procfs module
  05_debug/README.md
  05_debug/up_converter/Makefile
  05_debug/up_converter/test.log
  05_debug/up_converter/test_up_converter.sh
  05_debug/up_converter/up_converter.c
Labels: Ready for review

#62 05 debug sysfs homework
  05_debug/low_converter/Makefile
  05_debug/low_converter/low_converter.c
  05_debug/low_converter/test.log
  05_debug/low_converter/test_low_converter.sh
Labels: Ready for review

#61 05_debug: sysfs and procfs module implementation
  05_debug/README.md
  05_debug/logs/procfs.log
  05_debug/logs/sysfs.log
  05_debug/procfs_uppercase_conv/Makefile
  05_debug/procfs_uppercase_conv/khmod.c
  05_debug/procfs_uppercase_conv/test.sh
  05_debug/sysfs_lowercase_conv/Makefile
  05_debug/sysfs_lowercase_conv/khmod.c
  05_debug/sysfs_lowercase_conv/test.sh
Labels: Ready for review

#67 06_timers time from previous call module
  06_timers/02_time_from_prev/Makefile
  06_timers/02_time_from_prev/test.log
  06_timers/02_time_from_prev/test.sh
  06_timers/02_time_from_prev/time_fprev.c
  06_timers/README.md
Labels: Ready for review

#66 06_timers absolute time user space program
  06_timers/01_absolute_time/Makefile
  06_timers/01_absolute_time/main.c
Labels: Ready for review

#65 05_debug: Kernel debugging homework
  05_debug/Makefile
  05_debug/README.md
  05_debug/build_install.sh
  05_debug/debug_comm.c
  05_debug/debug_comm.h
  05_debug/debug_procfs.c
  05_debug/debug_procfs.h
  05_debug/debug_sysfs.c
  05_debug/debug_sysfs.h
  05_debug/debug_task.c
Labels: Ready for review

#49 Linked list implementation
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/module_log.rst
  04_basic_struct/task_04.c
Labels: Change requested, Ready for review

#41 Module homework
  03_module/Makefile
  03_module/README.md
  03_module/module_log.txt
  03_module/test_module.c
Labels: Ready for review

#69 06_timers: task solution
  06_timers/README.md
  06_timers/kmodule/Makefile
  06_timers/kmodule/checkpatch.log
  06_timers/kmodule/timer_module.c
  06_timers/kmodule/timer_module.log
  06_timers/uspace/checkpatch.log
  06_timers/uspace/main.c
  06_timers/uspace/makefile
  06_timers/uspace/uspace.log
Labels: Ready for review

#79 Task 3
  hwdetect/README.md
  hwdetect/hwdetect.sh
  task_3/Makefile
  task_3/firstmod.c
Labels: Ready for review

#83 Task 01
  scissors/Makefile
  scissors/README.md
  scissors/scissors.c
Labels: Ready for review

#72 04_basic_struct module with linked list
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/basic_struct.c
  04_basic_struct/test.log
  04_basic_struct/test.sh
Labels: Ready for review

#75 06_timers: Timers homework
  06_timers/README.md
  06_timers/build_install.sh
  06_timers/komod/Makefile
  06_timers/komod/timers_task.c
  06_timers/user/Makefile
  06_timers/user/timers_task.c
Labels: Ready for review

#77 03_module: Add first kernel module
  03_module/03_module.c
  03_module/03_module.log
  03_module/Makefile
Labels: Ready for review

#76 Task_06: Timers
  06_timers/kernel_module/BBB_log_timers.txt
  06_timers/kernel_module/Makefile
  06_timers/kernel_module/checkpatch.log
  06_timers/kernel_module/sysfs_timer_module.c
  06_timers/userspace_script/Makefile
  06_timers/userspace_script/show_time.c
Labels: Ready for review

#84 Task 02
  hwdetect/README.md
  hwdetect/hwdetect.sh
Labels: Ready for review

#86 Add first module
  03_module/Makefile
  03_module/README.md
  03_module/checkpatch.log
  03_module/lkm_example.c
  03_module/lkm_example.log
Labels: Change requested, Ready for review

#87 Task_06: user and kernel space timers implementation
  06_timers/README.md
  06_timers/kernel_time/Makefile
  06_timers/kernel_time/khmod.c
  06_timers/kernel_time/test.sh
  06_timers/logs/sysfs_time.log
  06_timers/logs/user_time.log
  06_timers/user_time/Makefile
  06_timers/user_time/main
  06_timers/user_time/main.c
Labels: Ready for review

#88 Timers homework
  06_timers/Makefile
  06_timers/README.md
  06_timers/current_time.log
  06_timers/kernel_time.log
  06_timers/time.c
  06_timers/timers_module.c
Labels: Ready for review

#85 Sysfs debug hw
  05_debug/Makefile
  05_debug/README.md
  05_debug/debug_info.log
  05_debug/debug_module.c
Labels: WIP

#90 Task 06 userspace timer implementation
  06_timers/README.md
  06_timers/userspace_time/Makefile
  06_timers/userspace_time/logs.rst
  06_timers/userspace_time/task_06.c
Labels: Ready for review

#97 GPIO poll solution
  08_irq/README.md
  08_irq/gpio_poll/Makefile
  08_irq/gpio_poll/gpio_poll.c
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
Labels: Ready for review

#101 Task 07 kernelspace memory tests implementation
  07_memory/README.md
  07_memory/kernel_mem/Makefile
  07_memory/kernel_mem/kernel_mem.c
  07_memory/kernel_mem/module_log.rst
Labels: Ready for review

#99 Basic data structure hw
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/data_list.c
  04_basic_struct/list_structure.log
Labels: Ready for review

#95 08_irq: task solution
  08_irq/README.md
  08_irq/irq/Makefile
  08_irq/irq/checkpatch.log
  08_irq/irq/gpio_irq.c
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
  08_irq/poll/Makefile
  08_irq/poll/checkpatch.log
  08_irq/poll/gpio_poll.c
Labels: Ready for review

#113 07_memory: Memory homework
  07_memory/README.md
  07_memory/build_install.sh
  07_memory/komod/Makefile
  07_memory/komod/gl_time.h
  07_memory/komod/memory_task.c
  07_memory/komod/memory_task.h
  07_memory/komod/memory_task_beaglebone.log
  07_memory/user/Makefile
  07_memory/user/memory_task.c
  07_memory/user/memory_task_beaglebone.log
  07_memory/user/memory_task_laptop.log
Labels: Ready for review

#105 Task 07: Memory
  07_memory/README.md
  07_memory/kernel_module/BBB_log_memory.txt
  07_memory/kernel_module/Makefile
  07_memory/kernel_module/checkpatch.log
  07_memory/kernel_module/memory_test_module.c
  07_memory/userspace_script/BBB_log_userspace.txt
  07_memory/userspace_script/Makefile
  07_memory/userspace_script/memory.c
Labels: Ready for review

#120 DTS solution
  09_dt_rtc/README.md
  09_dt_rtc/hw/eeprom.log
  09_dt_rtc/hw/eeprom.patch
  09_dt_rtc/hw/rtc.log
  09_dt_rtc/hw/rtc.patch
  09_dt_rtc/images/BBB-RTC.jpg
Labels: Ready for review

#73 Task 05 sysfs implementation
  05_debug/README.md
  05_debug/sysfs/Makefile
  05_debug/sysfs/module_log.rst
  05_debug/sysfs/task_05_sysfs.c
  05_debug/sysfs/test.sh
Labels: Change requested, Ready for review

#117 Task 08 poll button implementation
  08_irq/README.md
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
  08_irq/poll/Makefile
  08_irq/poll/_clang-format
  08_irq/poll/gpio_poll.c
Labels: Ready for review

#89 07_memory: solution implementation
  07_memory/README.md
  07_memory/kmodule/Makefile
  07_memory/kmodule/checkpatch.log
  07_memory/kmodule/memory_module.c
  07_memory/kmodule/memory_module.log
  07_memory/uspace/checkpatch.log
  07_memory/uspace/main.c
  07_memory/uspace/makefile
Labels: Ready for review

#108 module homework
  03_module/Makefile
  03_module/README.md
  03_module/checkpatch.log
  03_module/kernel-log.sh
  03_module/kernel.log
  03_module/main.c
Labels: Ready for review

#125 09_mpu6050: Script implementation
  09_mpu6050_user/README.md
  09_mpu6050_user/mpu_monitor.log
  09_mpu6050_user/mpu_monitor.sh
Labels: Ready for review

#93 07_memory user space testing program
  07_memory/01_uspace_mesure_time/Makefile
  07_memory/01_uspace_mesure_time/main.c
  07_memory/01_uspace_mesure_time/test.log
  07_memory/README.md
Labels: Ready for review

#124 Task 8: IRQ
  08_irq/README.md
  08_irq/gpio_irq/BBB_log_irq.txt
  08_irq/gpio_irq/Makefile
  08_irq/gpio_irq/checkpatch.log
  08_irq/gpio_irq/gpio_irq.c
  08_irq/gpio_poll/Makefile
  08_irq/gpio_poll/checkpatch.log
  08_irq/gpio_poll/gpio_poll.c
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
Labels: Ready for review

#122 08_irq: Interrupt handling homework
  08_irq/README.md
  08_irq/build_install.sh
  08_irq/komod/gl_gpio/gl_gpio.c
  08_irq/komod/gl_gpio/gl_gpio.h
  08_irq/komod/gpio_irq/Makefile
  08_irq/komod/gpio_irq/gpio_irq_task.c
  08_irq/komod/gpio_poll/Makefile
  08_irq/komod/gpio_poll/gpio_poll_task.c
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
Labels: Ready for review

#131 05_debug: Add converter to lowercase and uppercase
  05_debug/procfs_task/05_debug_procfs.c
  05_debug/procfs_task/Makefile
  05_debug/sysfs_task/05_debug_sysfs.c
  05_debug/sysfs_task/Makefile
Labels: Ready for review

#111 Memory menagement HW: User space solution
  07_memory/Makefile
  07_memory/README.md
  07_memory/usr_mem_test.c
  07_memory/usr_mem_test.log
Labels: Ready for review

#103 Task03
  03_module/Makefile
  03_module/README.md
  03_module/firstmod.c
  03_module/logs.txt
Labels: Ready for review

#133 Chardev solution
  10_cdev/Makefile
  10_cdev/README.md
  10_cdev/chdev.c
  10_cdev/log.txt
  10_cdev/test.sh
Labels: Ready for review

#104 Task04
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/logs.txt
  04_basic_struct/task04.c
Labels: Ready for review

#116 Task_09 results
  09_dt_rtc/README.md
  09_dt_rtc/images/BBB-RTC.jpg
  09_dt_rtc/patches/0001-09_dt_rtc-Add-ds3231-support.patch
  09_dt_rtc/patches/0002-09_dt_rtc-Change-default-eeprom3-to-AT24C32.patch
  09_dt_rtc/results/eeprom.log
  09_dt_rtc/results/rtc.log
Labels: Ready for review

#138 10_cdev: Character devices homework
  10_cdev/README.md
  10_cdev/build_install.sh
  10_cdev/komod/cdev/Makefile
  10_cdev/komod/cdev/cdev_task.c
  10_cdev/komod/cdev/gl_msg_buf.h
  10_cdev/komod/cdev/gl_procfs.c
  10_cdev/komod/cdev/gl_procfs.h
  10_cdev/komod/cdev/gl_sysfs.c
  10_cdev/komod/cdev/gl_sysfs.h
  10_cdev/komod/test/cdev_test.log
  10_cdev/komod/test/cdev_test.sh
Labels: Ready for review

#106 08_irq add check button linux kernel module
  08_irq/01_check_button/Makefile
  08_irq/01_check_button/check_button.c
  08_irq/01_check_button/test.log
  08_irq/README.md
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
Labels: Ready for review

#128 04 basic struct
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/checkpatch.log
  04_basic_struct/lkm_example.c
  04_basic_struct/lkm_example.log
Labels: Ready for review

#123 09_dt_rts: execution results
  09_dt_rtc/0001-DTS-add-rtc-ds3231-to-the-device-tree.patch
  09_dt_rtc/0002-DTS-set-cape_eprom3-0x57-to-AT24C32.patch
  09_dt_rtc/README.md
  09_dt_rtc/eeprom_ops.log
  09_dt_rtc/i2c_detection.log
  09_dt_rtc/images/BBB-RTC.jpg
  09_dt_rtc/rtc_ops.log
Labels: Ready for review

#150 RTC DS3231 driver solution
  11_rtc_driver/Makefile
  11_rtc_driver/README.md
  11_rtc_driver/ds3132_regmap.h
  11_rtc_driver/log.txt
  11_rtc_driver/rtc.patch
  11_rtc_driver/rtc_drv.c
Labels: Ready for review

#137 Task 10 character device implementation
  10_cdev/.gitignore
  10_cdev/Makefile
  10_cdev/README.md
  10_cdev/cdev.c
  10_cdev/module_log.rst
  10_cdev/test.sh
Labels: Ready for review

#130 Task 09 dts
  09_dt_rtc/README.md
  09_dt_rtc/diff.rst
  09_dt_rtc/logs.rst
Labels: Ready for review

#147 Interrupt handling HW: gpio irq solution
  08_irq/README.md
  08_irq/gpio_irq/Makefile
  08_irq/gpio_irq/gpio_irq.c
  08_irq/gpio_irq/irq_log.txt
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
Labels: Ready for review

#145 11_rtc_drv: task solution
  11_rtc_driver/0001-PATCH-DTS-add-rtc-ds3231x-to-the-device-tree.patch
  11_rtc_driver/Makefile
  11_rtc_driver/README.md
  11_rtc_driver/checkpatch.log
  11_rtc_driver/ds3231_regs.h
  11_rtc_driver/ds3231x_drv.c
Labels: Ready for review

#142 09_dt_rtc add ds3231 device tree patch
  09_dt_rtc/01_rtc/0001-09_dt_rtc-add-rtc-ds3231-to-the-device-tree.patch
  09_dt_rtc/01_rtc/file.log
  09_dt_rtc/README.md
  09_dt_rtc/images/BBB-RTC.jpg
Labels: Ready for review

#149 10_cdev add character device linux kernel module
  10_cdev/Makefile
  10_cdev/README.md
  10_cdev/chdev_common.h
  10_cdev/chrdev.c
  10_cdev/procfs_entry.c
  10_cdev/procfs_entry.h
  10_cdev/sysfs_entry.c
  10_cdev/sysfs_entry.h
  10_cdev/test.log
  10_cdev/test.sh
Labels: Ready for review

#110 Task_08 module implementation
  08_irq/README.md
  08_irq/irq_button/Makefile
  08_irq/irq_button/khmod.c
  08_irq/onboard_io_demo/Makefile
  08_irq/onboard_io_demo/onboard_io.c
  08_irq/poll_button/Makefile
  08_irq/poll_button/khmod.c
Labels: Ready for review

#154 Task_10: Chardev implementation
  10_cdev/Makefile
  10_cdev/README.md
  10_cdev/khmod.c
  10_cdev/log/cdev.log
  10_cdev/test.sh
Labels: Ready for review

#158 Task_11: ds3231x driver implementation
  11_rtc_driver/Makefile
  11_rtc_driver/README.md
  11_rtc_driver/ds3231.h
  11_rtc_driver/khmod.c
  11_rtc_driver/log/ds3231.log
Labels: Ready for review

#132 05_debug module HW
  05_debug/Makefile
  05_debug/README.md
  05_debug/checkpatch.log
  05_debug/deb_module.c
  05_debug/deb_module.log
Labels: Ready for review

#157 11_rtc_driver add rtc driver for ds3231x device
  11_rtc_driver/0001-11_rtc_driver-add-rtc-overlay-and-description-for-th.patch
  11_rtc_driver/Makefile
  11_rtc_driver/README.md
  11_rtc_driver/file.log
  11_rtc_driver/rtc_ds3231x.c
  11_rtc_driver/test.sh
Labels: Ready for review

#146 Task 11 RTC driver implementation
  11_rtc_driver/.gitignore
  11_rtc_driver/Makefile
  11_rtc_driver/README.md
  11_rtc_driver/diff.rst
  11_rtc_driver/driver.c
  11_rtc_driver/ds3231.h
  11_rtc_driver/module_log.rst
  11_rtc_driver/test.sh
Labels: Ready for review

#163 Task11
  11_rtc_driver/Makefile
  11_rtc_driver/README.md
  11_rtc_driver/ds3231.h
  11_rtc_driver/rtc.txt
  11_rtc_driver/task11.c
  README.md
Labels: Ready for review

#160 Add 06_timers HW
  06_timers/README.md
  06_timers/Task1/Makefile
  06_timers/Task1/checkpatch.log
  06_timers/Task1/main.c
  06_timers/Task1/main.log
  06_timers/Task2/Makefile
  06_timers/Task2/checkpatch.log
  06_timers/Task2/tim_module.c
  06_timers/Task2/tim_module.log
  06_timers/Task3/Makefile
  06_timers/Task3/checkpatch.log
  06_timers/Task3/tim_module.c
  06_timers/Task3/tim_module.log
Labels: Ready for review
